window.BND_PETS = [
  {
    id: "rj",
    name: "RJ",
    member: "BT21",
    animalType: "alpaca desktop mascot",
    personality: ["gentle", "warm", "fluffy", "sweet"],
    favoriteItem: "red scarf",
    favoriteFood: "cozy snacks",
    visualStyle: "2D chibi BT21 desktop pet with clean sticker styling.",
    bubbleText: ["RJ is here.", "Warm and fluffy."],
    voiceLine: "cozy-rj",
    animations: {
      idle: "Soft breathing loop.",
      "running-right": "Tiny rightward trot.",
      "running-left": "Tiny leftward trot.",
      waving: "Friendly wave.",
      jumping: "Small happy hop.",
      failed: "Brief worried beat.",
      waiting: "Patient sway.",
      running: "Busy little work loop.",
      review: "Focused inspection pose."
    },
    theme: { primary: "#fff8ed", secondary: "#df3d36", accent: "#4c3428" },
    ready: true
  },
  {
    id: "koya",
    name: "Koya",
    member: "BT21",
    animalType: "koala desktop mascot",
    personality: ["thoughtful", "sleepy", "clever", "calm"],
    favoriteItem: "tiny pillow",
    favoriteFood: "dream snacks",
    visualStyle: "2D chibi BT21 desktop pet with clean sticker styling.",
    bubbleText: ["Thinking softly.", "Nap-powered ideas."],
    voiceLine: "dream-koya",
    animations: {
      idle: "Gentle blink and breathing loop.",
      "running-right": "Tiny rightward run.",
      "running-left": "Tiny leftward run.",
      waving: "Small greeting wave.",
      jumping: "Compact happy hop.",
      failed: "Small dizzy pause.",
      waiting: "Quiet waiting sway.",
      running: "Focused busy loop.",
      review: "Careful checking pose."
    },
    theme: { primary: "#edf8ff", secondary: "#74bce8", accent: "#203d6b" },
    ready: true
  },
  {
    id: "shooky",
    name: "Shooky",
    member: "BT21",
    animalType: "cookie desktop mascot",
    personality: ["mischievous", "bold", "tiny", "funny"],
    favoriteItem: "crumb trail",
    favoriteFood: "cookies",
    visualStyle: "2D chibi BT21 desktop pet with clean sticker styling.",
    bubbleText: ["Hehe.", "Tiny but loud."],
    voiceLine: "crumb-shooky",
    animations: {
      idle: "Playful breathing loop.",
      "running-right": "Quick rightward scoot.",
      "running-left": "Quick leftward scoot.",
      waving: "Cheeky wave.",
      jumping: "Tiny hop.",
      failed: "Mischievous stumble.",
      waiting: "Restless sway.",
      running: "Busy dash loop.",
      review: "Suspicious checking pose."
    },
    theme: { primary: "#fff0dc", secondary: "#8a5a36", accent: "#2f1f18" },
    ready: true
  },
  {
    id: "mang",
    name: "MANG",
    member: "BT21",
    animalType: "masked dancer desktop mascot",
    personality: ["rhythmic", "bright", "playful", "confident"],
    favoriteItem: "dance beat",
    favoriteFood: "stage candy",
    visualStyle: "2D chibi BT21 desktop pet with clean sticker styling.",
    bubbleText: ["Beat on.", "MANG moves."],
    voiceLine: "dance-mang",
    animations: {
      idle: "Gentle loop with dancer energy.",
      "running-right": "Rightward dance run.",
      "running-left": "Leftward dance run.",
      waving: "Rhythmic greeting.",
      jumping: "Springy hop.",
      failed: "Short wronged beat.",
      waiting: "Ready-to-dance sway.",
      running: "Busy motion loop.",
      review: "Alert inspection pose."
    },
    theme: { primary: "#f3efff", secondary: "#9b80e8", accent: "#2e336f" },
    ready: true
  },
  {
    id: "chimmy",
    name: "Chimmy",
    member: "BT21",
    animalType: "hooded puppy desktop mascot",
    personality: ["cheerful", "earnest", "sunny", "loyal"],
    favoriteItem: "yellow hood",
    favoriteFood: "bright treats",
    visualStyle: "2D chibi BT21 desktop pet with clean sticker styling.",
    bubbleText: ["Let's go.", "Chimmy time."],
    voiceLine: "sunny-chimmy",
    animations: {
      idle: "Soft blink and sway.",
      "running-right": "Happy rightward run.",
      "running-left": "Happy leftward run.",
      waving: "Warm wave.",
      jumping: "Cheerful hop.",
      failed: "Tiny disappointed beat.",
      waiting: "Patient sway.",
      running: "Energetic work loop.",
      review: "Curious checking pose."
    },
    theme: { primary: "#fff8d8", secondary: "#f1c84c", accent: "#111111" },
    ready: true
  },
  {
    id: "tata",
    name: "Tata",
    member: "BT21",
    animalType: "heart-headed desktop mascot",
    personality: ["curious", "cosmic", "expressive", "sweet"],
    favoriteItem: "heart signal",
    favoriteFood: "space snacks",
    visualStyle: "2D chibi BT21 desktop pet with clean sticker styling.",
    bubbleText: ["Heart signal on.", "From planet BT."],
    voiceLine: "heart-tata",
    animations: {
      idle: "Gentle heart-headed idle loop.",
      "running-right": "Tiny rightward run.",
      "running-left": "Tiny leftward run.",
      waving: "Big friendly wave.",
      jumping: "Bright hop.",
      failed: "Surprised pause.",
      waiting: "Curious waiting sway.",
      running: "Busy cosmic loop.",
      review: "Focused checking pose."
    },
    theme: { primary: "#fff1ee", secondary: "#e8443f", accent: "#255fba" },
    ready: true
  },
  {
    id: "cooky",
    name: "Cooky",
    member: "BT21",
    animalType: "bunny desktop mascot",
    personality: ["tough", "cute", "energetic", "confident"],
    favoriteItem: "blue dumbbell",
    favoriteFood: "power snacks",
    visualStyle: "2D chibi BT21 desktop pet with clean sticker styling.",
    bubbleText: ["Power up.", "Cute and strong."],
    voiceLine: "power-cooky",
    animations: {
      idle: "Confident breathing loop.",
      "running-right": "Quick rightward sprint.",
      "running-left": "Quick leftward sprint.",
      waving: "Bold wave.",
      jumping: "Energetic hop.",
      failed: "Tiny tough pout.",
      waiting: "Ready stance.",
      running: "Workout loop.",
      review: "Sharp inspection pose."
    },
    theme: { primary: "#fff0f8", secondary: "#f58cbd", accent: "#3c7cd8" },
    ready: true
  },
  {
    id: "van",
    name: "Van",
    member: "BT21",
    animalType: "guardian desktop mascot",
    personality: ["steady", "quiet", "protective", "kind"],
    favoriteItem: "guardian glow",
    favoriteFood: "starlight",
    visualStyle: "2D chibi BT21 desktop pet with clean sticker styling.",
    bubbleText: ["Watching over you.", "Van is steady."],
    voiceLine: "guardian-van",
    animations: {
      idle: "Calm breathing loop.",
      "running-right": "Smooth rightward glide.",
      "running-left": "Smooth leftward glide.",
      waving: "Gentle greeting.",
      jumping: "Small steady hop.",
      failed: "Brief static beat.",
      waiting: "Quiet guard sway.",
      running: "Focused motion loop.",
      review: "Careful inspection pose."
    },
    theme: { primary: "#f6f7f8", secondary: "#b6bcc4", accent: "#222222" },
    ready: true
  }
];
